export const companyNames = [
  "Apple",
  "Microsoft",
  "Amazon",
  "Alphabet",
  "Meta",
  "Tesla",
  "Nvidia",
  //   "Berkshire Hathaway",
  //   "JPMorgan Chase",
  //   "Johnson & Johnson",
  "Visa",
  //   "Procter & Gamble",
  "Walmart",
  "Mastercard",
  //   "UnitedHealth",
  //   "Home Depot",
  //   "Exxon Mobil",
  "Chevron",
  "Coca-Cola",
  "PepsiCo",
  "Nike",
  //   "McDonald's",
  "Disney",
  "Netflix",
  "Adobe",
  "Salesforce",
  "Intel",
  "Cisco",
  "Oracle",
  "IBM",
  "Boeing",
  "Caterpillar",
  "3M",
  //   "Goldman Sachs",
  //   "American Express",
  "Pfizer",
  "Merck",
  //   "Abbott Laboratories",
  "Costco",
  "Target",
];
