export const pricingPlans = [
  {
    name: "Trader 🚀 ",
    monthlyPrice: "$29.99",
    annualPrice: "$299.99",
    features: [
      "Live Earnings Calendar",
      "Earnings Expectations vs. Reported Numbers",
      "Earnings Reports from 5+ years",
      "News on Thousands of Tickers",
      "Company Earnings Reports",
      "Daily News Digest",
      "Weekly News Digest",
    ],
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_TRADER_PRICE_ID,
    priceIdYearly: process.env.NEXT_PUBLIC_STRIPE_YEARLY_TRADER_PRICE_ID,
    actionLabel: "Get Started",
  },
  {
    name: "API ⚡",
    monthlyPrice: "$199.99",
    annualPrice: "$1,919.90",
    features: [
      "All US Stocks Tickers",
      "Unlimited API Calls",
      "5 Years Historical Earnings Data",
      "100% Market Coverage",
      "Searchable data",
      "Unlimited File Downloads",
      "Claude integration",
      "Fundamentals Data",
      "WebSockets",
      "Snapshot",
    ],
    actionLabel: "Get Started",
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_API_PRICE_ID,
    priceIdYearly: process.env.NEXT_PUBLIC_STRIPE_YEARLY_API_PRICE_ID,
    popular: true,
  },
];
