export const pricingPlans = [
  {
    name: "Trader",
    monthlyPrice: "$29.99",
    annualPrice: "$299.99",
    features: [
      "Updated Earnings Calendar",
      "Estimates vs. Actuals",
      "Earnings Reports from 15+ years",
      "100% Market Coverage",
      "Downloadable Transcripts",
      "Live call streaming",
      "Claude generated summaries",
      "Weekly Newsletter",
      "24/7 Support",
    ],
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_TRADER_PRICE_ID,
    priceIdYearly: process.env.NEXT_PUBLIC_STRIPE_YEARLY_TRADER_PRICE_ID,
    actionLabel: "Get Started",
  },
  {
    name: "API",
    monthlyPrice: "$199.99",
    annualPrice: "$1,919.90",
    features: [
      "100% Market Coverage",
      "Date and Time Earnings End Points",
      "Unlimited API Calls",
      "15+ Years Historical Data",
      "EPS and Rev Est and Actual",
      "Logo and Ticker End Points",
      "Audio of 220K conference calls",
      "Dedicated Slack Channel",
      "Founder led Customer Success",
    ],
    actionLabel: "Get Started",
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_MONTHLY_API_PRICE_ID,
    priceIdYearly: process.env.NEXT_PUBLIC_STRIPE_YEARLY_API_PRICE_ID,
    popular: true,
  },
];
